# Generated by Django 2.2.10 on 2020-02-15 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doenca',
            fields=[
                ('id', models.IntegerField()),
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Prevencao',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('name', models.CharField(max_length=60)),
                ('publica', models.CharField(max_length=100)),
                ('senha', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Sintoma',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Sessao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doenca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dissecadores.Doenca')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dissecadores.Sala')),
            ],
        ),
        migrations.AddField(
            model_name='doenca',
            name='prevencao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dissecadores.Prevencao'),
        ),
        migrations.AddField(
            model_name='doenca',
            name='sintoma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dissecadores.Sintoma'),
        ),
    ]
