# Generated by Django 2.2.10 on 2020-02-20 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doenca',
            fields=[
                ('ident', models.IntegerField()),
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Prevencao',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('publica', models.CharField(max_length=100)),
                ('senha', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sintoma',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Sessao',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('doencas', models.ManyToManyField(to='dissecadores.Doenca')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dissecadores.Sala')),
            ],
        ),
        migrations.AddField(
            model_name='doenca',
            name='prevencoes',
            field=models.ManyToManyField(to='dissecadores.Prevencao'),
        ),
        migrations.AddField(
            model_name='doenca',
            name='sintomas',
            field=models.ManyToManyField(to='dissecadores.Sintoma'),
        ),
    ]
